remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: 0x4248 wiki
description: A collection of guides and tutorials for various topics that I have written. 
show_downloads: false